# heavily inspired by https://github.com/remarkablemark/react-native-cli-quickstart/blob/8408c92455a42737c106d96ba78d78232de866f2/.github/workflows/e2e-android.yml
name: android-detox

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string

jobs:
  check-affected:
    runs-on: ubuntu-latest
    outputs:
      affecteds: ${{ steps.affecteds.outputs.affecteds }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions

      - run: yarn install --frozen-lockfile --prefer-offline

      - id: affecteds
        run: echo "affecteds=$(yarn --silent nx print-affected --target=test-android --projects=${{ inputs.app-name }}-e2e --configuration production --select=projects)" | tee -a $GITHUB_OUTPUT

  android-detox:
    runs-on: macos-latest
    needs: check-affected
    timeout-minutes: 120
    if: needs.check-affected.outputs.affecteds != ''
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions

      - run: yarn install --frozen-lockfile --prefer-offline

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('apps/${{ inputs.app-name }}/**/*.gradle*', 'apps/${{ inputs.app-name }}/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - uses: actions/cache@v3
        with:
          path: apps/${{ inputs.app-name }}/android/app/build
          key: ${{ runner.os }}-detox-${{ inputs.app-name }}-android-build
          restore-keys: |
            ${{ runner.os }}-detox-${{ inputs.app-name }}-android-build

      - run: yarn nx ensure-symlink ${{ inputs.app-name }}

      - run: yarn nx run ${{ inputs.app-name }}-e2e:build-android --configuration production --verbose

      - id: device
        run: (cd apps/${{ inputs.app-name }}-e2e && node -e "console.log('AVD_NAME=' + require('./.detoxrc').devices.emulator.device.avdName)" | tee -a $GITHUB_OUTPUT)

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-boot-timeout: 1800
          api-level: 31
          arch: x86_64
          avd-name: ${{ steps.device.outputs.AVD_NAME }}
          script: yarn nx run ${{ inputs.app-name }}-e2e:test-android --configuration production --headless --record-logs all --reuse false --build-target= --verbose

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detox-artifacts
          path: apps/${{ inputs.app-name }}-e2e/artifacts
