# heavily inspired by https://github.com/remarkablemark/react-native-cli-quickstart/blob/8408c92455a42737c106d96ba78d78232de866f2/.github/workflows/e2e-android.yml
name: android-detox
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-detox:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions

      - run: yarn install --frozen-lockfile --prefer-offline

      - id: affecteds
        run: yarn --silent nx print-affected --target=test-android --projects=todo-app-e2e --configuration production | jq '.projects | length'

      - uses: actions/setup-java@v3
        if: ${{ steps.affecteds.outputs.stdout }} > 0
        with:
          cache: gradle
          distribution: zulu
          java-version: 11

      - run: yarn nx run todo-app-e2e:build-android --configuration production --verbose
        if: ${{ steps.affecteds.outputs.stdout }} > 0

      - id: device
        run: (cd apps/todo-app-e2e && node -e "console.log('AVD_NAME=' + require('./.detoxrc').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT)
        if: ${{ steps.affecteds.outputs.stdout }} > 0

      - uses: reactivecircus/android-emulator-runner@v2
        if: ${{ steps.affecteds.outputs.stdout }} > 0
        with:
          api-level: 31
          arch: x86_64
          avd-name: ${{ steps.device.outputs.AVD_NAME }}
          script: yarn nx run todo-app-e2e:test-android --configuration production --headless --record-logs all --reuse false --verbose --build-target=

      - uses: actions/upload-artifact@v3
        if: ${{ steps.affecteds.outputs.stdout }} > 0 && failure()
        with:
          name: detox-artifacts
          path: apps/todo-app-e2e/artifacts
