# https://github.com/remarkablemark/react-native-cli-quickstart/blob/8408c92455a42737c106d96ba78d78232de866f2/.github/workflows/e2e-ios.yml
name: ios-detox
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ios-detox:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions

      - run: yarn --frozen-lockfile --prefer-offline

      - id: affecteds
        run: yarn --silent nx print-affected --target=test-ios --projects=todo-app-e2e --configuration production | jq '.projects | length'

      - id: cache-macos-deps
        uses: actions/cache@v3
        if: ${{ steps.affecteds.outputs.stdout }} > 0
        with:
          path: /usr/local/Homebrew
          key: ${{ runner.os }}-macos-brew
          restore-keys: |
            ${{ runner.os }}-macos-brew

      - run: |
          brew tap wix/brew
          brew install applesimutils
        if: ${{ steps.affecteds.outputs.stdout }} > 0
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - uses: ruby/setup-ruby@v1
        if: ${{ steps.affecteds.outputs.stdout }} > 0
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - run: |
          node --version
          ruby --version
          pod --version
        if: ${{ steps.affecteds.outputs.stdout }} > 0

      - run: yarn nx ensure-symlink todo-app
        if: ${{ steps.affecteds.outputs.stdout }} > 0

      - id: cache-cocoapods
        if: ${{ steps.affecteds.outputs.stdout }} > 0
        uses: actions/cache@v3
        with:
          path: apps/todo-app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('apps/todo-app/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - run: pod install
        working-directory: apps/todo-app/ios
        if: ${{ steps.affecteds.outputs.stdout }} > 0 && steps.cache-cocoapods.outputs.cache-hit != 'true'

      - run: yarn detox rebuild-framework-cache
        if: ${{ steps.affecteds.outputs.stdout }} > 0
        working-directory: apps/todo-app-e2e

      - run: yarn nx run todo-app-e2e:build-ios --configuration production --verbose
        if: ${{ steps.affecteds.outputs.stdout }} > 0

      - run: yarn nx run todo-app-e2e:test-ios --configuration production --cleanup --headless --record-logs all --verbose --reuse false
        if: ${{ steps.affecteds.outputs.stdout }} > 0

      - uses: actions/upload-artifact@v3
        if: ${{ steps.affecteds.outputs.stdout }} > 0 && failure()
        with:
          name: detox-artifacts
          path: apps/todo-app-e2e/artifacts
