# https://github.com/remarkablemark/react-native-cli-quickstart/blob/8408c92455a42737c106d96ba78d78232de866f2/.github/workflows/e2e-ios.yml
name: ios-detox

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string

jobs:
  check-affected:
    runs-on: ubuntu-latest
    outputs:
      affecteds: ${{ steps.affecteds.outputs.affecteds }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions

      - run: yarn install --frozen-lockfile --prefer-offline

      - id: affecteds
        run: echo "affecteds=$(yarn --silent nx print-affected --target=test-ios --projects=${{ inputs.app-name }}-e2e --configuration production --select=projects)" | tee -a $GITHUB_OUTPUT

  ios-detox:
    runs-on: macos-latest
    needs: check-affected
    timeout-minutes: 120
    if: needs.check-affected.outputs.affecteds != ''
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions

      - run: yarn --frozen-lockfile --prefer-offline

      - id: cache-macos-deps
        uses: actions/cache@v3
        with:
          path: /usr/local/Homebrew
          key: ${{ runner.os }}-macos-brew
          restore-keys: |
            ${{ runner.os }}-macos-brew

      - run: |
          brew tap wix/brew
          brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - run: yarn nx ensure-symlink ${{ inputs.app-name }}

      - id: cache-cocoapods
        uses: actions/cache@v3
        with:
          path: apps/${{ inputs.app-name }}/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('apps/${{ inputs.app-name }}/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - run: pod install
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        working-directory: apps/${{ inputs.app-name }}/ios

      - run: yarn detox rebuild-framework-cache
        working-directory: apps/${{ inputs.app-name }}-e2e

      - uses: actions/cache@v3
        with:
          path: apps/${{ inputs.app-name }}/ios/build
          key: ${{ runner.os }}-detox-${{ inputs.app-name }}-ios-build
          restore-keys: |
            ${{ runner.os }}-detox-${{ inputs.app-name }}-ios-build

      - run: yarn nx run ${{ inputs.app-name }}-e2e:build-ios --configuration production --verbose

      - run: yarn nx run ${{ inputs.app-name }}-e2e:test-ios --configuration production --cleanup --headless --record-logs all --reuse false --build-target= --verbose

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detox-artifacts
          path: apps/${{ inputs.app-name }}-e2e/artifacts
